### ISSUE TITLE
"Convert" into a proper Python package

### ISSUE THREAD

**Issue by yarikoptic** [nicolocin/bonsairecordingextractor#3]
- [ ] convert to a proper python package with testing etc
- [ ] `test.py` into neuroconv/tests/basic.py (pytest)

**Comment by satra** [comment]
@yarikoptic that's a good start. 

after @jwodder  does this, @nicolocin  could you please help add the bonsai dataset to a datalad repo and then use it to add testing to the bonsai conversion script.

**Comment by satra** [comment]
actually let's create a common datalad dataset for raw data

**Comment by jwodder** [comment]
What exactly is `test.py` meant to be doing?  Does just getting to the end of the code indicate success, or should some `assert`s be added to it?

**Comment by yarikoptic** [comment]
@jwodder for now just indeed make it a "smoke test" -- just to be ran and not to fail.
